### ISSUE TITLE
Missing start hook

### ISSUE THREAD

**Issue by chuckbutler** [chuckbutler/docker-charm#21]
This has potential to cause issues when the host is restarted.

This begs attention to how can we discern what containers need to be restarted during a boot? Is this the responsibility of the docker charm itself or the image delivery charm (which doesn't currently exist)

**Comment by chuckbutler** [comment]
Suggested to place a restart policy in the docs, with an action to launch a container and call this good.

**Comment by johnsca** [comment]
It seems like the stop hook triggers uninstall-docker but start does not trigger install-or-upgrade.  If the cloud decides to bounce your instance (e.g., http://serverfault.com/questions/257148/ec2-rebooted-my-instance), it's going to end up in a broken state.  The charm really should handle that more gracefully, and I don't think that requiring manual intervention (via an action) is reasonable.

**Comment by chuckbutler** [comment]
@johnsca It wont break the charm - docker is controlled by an upstart job. the containers themselves are under the responsibility of the launching container process - be that an action, another charm, or ssh'ing into the unit and starting the container.

Having a 'start hook' to manage this is beyond the scope of what the charm is providing. this is infrastructure components, and managing the docker instance itself - not the containers.

**Comment by johnsca** [comment]
I completely misunderstood the start hook, apparently in a subconscious attempt to ascribe it some semblance of value as a hook.  You're absolutely right and I rescind my previous comment.
