### ISSUE TITLE
Bundle description code examples not showing up as code on jujucharms.com

### ISSUE THREAD

**Issue by hatched** [chuckbutler/docker-charm#26]
Some of the code examples aren't being shown as code on jujucharms.com. Under the heading 'Do some Dockering' https://jujucharms.com/u/lazypower/docker-core/4

https://github.com/chuckbutler/docker-bundle

**Comment by chuckbutler** [comment]
resolved with chuckbutler/docker-bundle v0.0.4 - pushed to BZR and will sync in ~ half an hour.
