### ISSUE TITLE
DockerOpts needs docs and tests

### ISSUE THREAD

**Issue by johnsca** [chuckbutler/docker-charm#54]
It's not at all obvious what the module is doing and why.  Docstring needs to be improved and tests added.

**Comment by chuckbutler** [comment]
@whitmo I've taken a stab at this - and I don't really understand how to test this python. I'm not sure if its a limitatin of how i read/write python or if you're being *really* clever here. I've refactored out the project to use tox as a testing platform. Can you take a look at committing tests for the DockerOptsManager?

**Comment by chuckbutler** [comment]
Resolved with commit 9f8752f43
