### ISSUE TITLE
Legal request - Remove Docker whale design mark from main page

### ISSUE THREAD

**Issue by cjpalermo** [chuckbutler/docker-charm#63]
Please remove the Docker whale trademark (logo) from the main page of docker-charm, as requested in our e-mail message of 13 July 2015.

Christopher J. Palermo
Attorneys for Docker, Inc.

**Comment by chuckbutler** [comment]
Sorry for the delay @cjpalermo - I've addressed the capitalization, and removed the tradename image from the Readme
