### ISSUE TITLE
network-relation-changed failed due to lxc-docker-{{version}} not a thing.

### ISSUE THREAD

**Issue by mbruzek** [chuckbutler/docker-charm#66]
I found a bug with the latest code, lxc-docker-{{verison}} went to docker-engine

unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 TASK: [Halt docker service] *************************************************** 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 failed: [localhost] => {"failed": true}
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 msg: service not found: False
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 FATAL: all hosts have already failed -- aborting
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 PLAY RECAP ******************************************************************** 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40            to retry, use: --limit @/root/site.yaml.retry
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 localhost                  : ok=9    changed=6    unreachable=0    failed=1   
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 Traceback (most recent call last):
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-docker-1/charm/hooks/network-relation-changed", line 14, in <module>
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40     main()
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-docker-1/charm/hooks/network-relation-changed", line 11, in main
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40     hooks.execute(args)
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-docker-1/charm/src/ansiblecharm/ansiblecharm/runner.py", line 216, in execute
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40     tags=tags, verbosity=verbosity, module_path=modules)
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-docker-1/charm/src/ansiblecharm/ansiblecharm/runner.py", line 129, in apply_playbook
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40     subprocess.check_call(call, env=env)
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40     raise CalledProcessError(retcode, cmd)
unit-docker-1[3649]: 2015-09-15 18:04:59 INFO unit.docker/1.network-relation-changed logger.go:40 subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', '-v', 'playbooks/site.yaml', '--tags', 'network-relation-ch
anged', '--module-path=/var/lib/juju/agents/unit-docker-1/charm/modules']' returned non-zero exit status 2
unit-docker-1[3649]: 2015-09-15 18:04:59 ERROR juju.worker.uniter.operation runhook.go:107 hook "network-relation-changed" failed: exit status 1

**Comment by chuckbutler** [comment]
Corrected as of tag v0.2.2

Thanks for finding/filing this bug @mbruzek
